namespace Shared.Enums
{
    public enum PacketType
    {
        //VehiclePositionData = 0,
        ChatData = 1,
        PlayerDisconnect = 2,
        //PedPositionData = 3,
        NpcVehPositionData = 4,
        ConnectionPacket = 5,
        WorldSharingStop = 6,
        DiscoveryResponse = 7,
        ConnectionRequest = 8,
        NativeCall = 9,
        NativeResponse = 10,
        PlayerRespawned = 11,
        NativeTick = 12,
        NativeTickRecall = 13,
        NativeOnDisconnect = 14,
        NativeOnDisconnectRecall = 15,
        CreateEntity = 16,
        DeleteEntity = 17,
        ScriptEventTrigger = 18,
        SyncEvent = 19,
        FileTransferTick = 20,
        FileTransferRequest = 21,
        FileTransferComplete = 22,
        ConnectionConfirmed = 23,
        PlayerKilled = 24,
        StopResource = 25,
        UpdateEntityProperties = 26,
        FileAcceptDeny = 27,
        ServerEvent = 28,
        RedownloadManifest = 29,
        PedPureSync = 30,
        PedLightSync = 31,
        VehiclePureSync = 32,
        VehicleLightSync = 33,
        BasicSync = 34,
        BulletSync = 35,
        UnoccupiedVehStartStopSync = 36,
        UnoccupiedVehSync = 37,
        BasicUnoccupiedVehSync = 38,
        BulletPlayerSync = 39,
        DeleteObject = 40,
    }
}
